rows: 3
title: '&0Vehicle'
fuel-display-item:
  slot: 12
  material: PLAYER_HEAD
  display-name: '&6Current Fuel'
  description:
  - ''
  - '&4{fuel_level} / {fuel_capacity} &6({fuel_level_percentage}%)'
  head-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGI4OWRlNDhhOWI4N2NmZDA3YzcwNGYyYmU1ZTVhOGNjNDVlODA3OWQzOGZhYWVkZjEzYjE1ZDE1YTEwYTcwYyJ9fX0=
pickup-item:
  slot: 0
  material: PLAYER_HEAD
  display-name: '&6Pick Up'
  description:
  - ''
  - '&6Click here to pick up'
  head-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTg5YWQ1MDJiNDc1NjIzZGVhYzAxZjBjZmY5NmY4NjUxZGQ2ZDkzYjEzNWMwYjU3NTQ4N2NhMGE0NTM5ZTcyIn19fQ==
seats-gui-item:
  slot: 14
  material: PLAYER_HEAD
  display-name: '&6Seats'
  head-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTI2ZWU4ZThiOWNiYThmODc2ZGM3NmY4ZmIwNjcwYjJhYmRjOTJjNjRlNGViNjc1ZWU0ZTU4MmRkYTQ4ZWZhOCJ9fX0=
seat-item:
  material: SADDLE
  display-name: '&6Passenger N°{seat_index} Seat'
operator-seat-item:
  material: PLAYER_HEAD
  display-name: '&4Operator Seat'
  head-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTI2ZWU4ZThiOWNiYThmODc2ZGM3NmY4ZmIwNjcwYjJhYmRjOTJjNjRlNGViNjc1ZWU0ZTU4MmRkYTQ4ZWZhOCJ9fX0=
